/**
 * e-RaktKosh Data Store: Seed datasets for Indian States, Districts,
 * Licensed Blood Centers, Voluntary Camps, Donors, and Blood Science Rules.
 */

window.eRaktKoshData = {
    // 1. States & Districts Data
    states: [
        {
            id: "DL",
            name: "Delhi (NCT)",
            districts: ["Central Delhi", "East Delhi", "New Delhi", "North Delhi", "South Delhi", "West Delhi"]
        },
        {
            id: "MH",
            name: "Maharashtra",
            districts: ["Mumbai City", "Mumbai Suburban", "Pune", "Nagpur", "Thane", "Nashik", "Aurangabad"]
        },
        {
            id: "KA",
            name: "Karnataka",
            districts: ["Bengaluru Urban", "Bengaluru Rural", "Mysuru", "Mangaluru", "Hubballi-Dharwad", "Belagavi"]
        },
        {
            id: "TN",
            name: "Tamil Nadu",
            districts: ["Chennai", "Coimbatore", "Madurai", "Tiruchirappalli", "Salem", "Vellore"]
        },
        {
            id: "UP",
            name: "Uttar Pradesh",
            districts: ["Lucknow", "Noida / Gautam Buddha Nagar", "Kanpur Nagar", "Varanasi", "Agra", "Prayagraj"]
        },
        {
            id: "WB",
            name: "West Bengal",
            districts: ["Kolkata", "Howrah", "North 24 Parganas", "South 24 Parganas", "Darjeeling", "Hooghly"]
        },
        {
            id: "TG",
            name: "Telangana",
            districts: ["Hyderabad", "Ranga Reddy", "Medchal-Malkajgiri", "Warangal", "Nizamabad"]
        },
        {
            id: "GJ",
            name: "Gujarat",
            districts: ["Ahmedabad", "Surat", "Vadodara", "Rajkot", "Bhavnagar", "Gandhinagar"]
        }
    ],

    // 2. Licensed Blood Banks Dataset
    bloodBanks: [
        {
            id: "BB-DL-01",
            name: "AIIMS Main Blood Bank",
            state: "Delhi (NCT)",
            district: "New Delhi",
            address: "Sri Aurobindo Marg, Ansari Nagar, New Delhi - 110029",
            contact: "011-26588500 / 011-26593201",
            type: "Government / Autonomous",
            category: "Major Regional Transfusion Center",
            lastUpdated: "Just now",
            inventory: {
                "A+": { "Whole Blood": 18, "PRBC": 24, "FFP": 30, "RDP": 15, "SDP": 4, "Cryoprecipitate": 8 },
                "A-": { "Whole Blood": 4, "PRBC": 6, "FFP": 12, "RDP": 2, "SDP": 1, "Cryoprecipitate": 2 },
                "B+": { "Whole Blood": 22, "PRBC": 35, "FFP": 40, "RDP": 18, "SDP": 6, "Cryoprecipitate": 10 },
                "B-": { "Whole Blood": 3, "PRBC": 5, "FFP": 8, "RDP": 2, "SDP": 1, "Cryoprecipitate": 2 },
                "AB+": { "Whole Blood": 12, "PRBC": 18, "FFP": 25, "RDP": 8, "SDP": 3, "Cryoprecipitate": 5 },
                "AB-": { "Whole Blood": 2, "PRBC": 3, "FFP": 6, "RDP": 1, "SDP": 0, "Cryoprecipitate": 1 },
                "O+": { "Whole Blood": 30, "PRBC": 45, "FFP": 50, "RDP": 22, "SDP": 8, "Cryoprecipitate": 12 },
                "O-": { "Whole Blood": 5, "PRBC": 8, "FFP": 14, "RDP": 3, "SDP": 2, "Cryoprecipitate": 4 },
                "BOMBAY": { "Whole Blood": 1, "PRBC": 2, "FFP": 2, "RDP": 0, "SDP": 0, "Cryoprecipitate": 0 }
            }
        },
        {
            id: "BB-DL-02",
            name: "Indian Red Cross Society Blood Center",
            state: "Delhi (NCT)",
            district: "Central Delhi",
            address: "1 Red Cross Road, New Delhi - 110001",
            contact: "011-23711551",
            type: "Charitable / Red Cross",
            category: "Model Blood Bank",
            lastUpdated: "12 mins ago",
            inventory: {
                "A+": { "Whole Blood": 14, "PRBC": 18, "FFP": 20, "RDP": 10, "SDP": 2, "Cryoprecipitate": 4 },
                "A-": { "Whole Blood": 2, "PRBC": 4, "FFP": 6, "RDP": 1, "SDP": 0, "Cryoprecipitate": 1 },
                "B+": { "Whole Blood": 19, "PRBC": 28, "FFP": 30, "RDP": 14, "SDP": 4, "Cryoprecipitate": 6 },
                "B-": { "Whole Blood": 1, "PRBC": 3, "FFP": 5, "RDP": 1, "SDP": 0, "Cryoprecipitate": 1 },
                "AB+": { "Whole Blood": 8, "PRBC": 12, "FFP": 15, "RDP": 5, "SDP": 2, "Cryoprecipitate": 3 },
                "AB-": { "Whole Blood": 1, "PRBC": 2, "FFP": 4, "RDP": 0, "SDP": 0, "Cryoprecipitate": 0 },
                "O+": { "Whole Blood": 25, "PRBC": 38, "FFP": 42, "RDP": 16, "SDP": 5, "Cryoprecipitate": 8 },
                "O-": { "Whole Blood": 3, "PRBC": 6, "FFP": 9, "RDP": 2, "SDP": 1, "Cryoprecipitate": 2 },
                "BOMBAY": { "Whole Blood": 0, "PRBC": 0, "FFP": 0, "RDP": 0, "SDP": 0, "Cryoprecipitate": 0 }
            }
        },
        {
            id: "BB-MH-01",
            name: "KEM Hospital Blood Bank",
            state: "Maharashtra",
            district: "Mumbai City",
            address: "Acharya Donde Marg, Parel, Mumbai - 400012",
            contact: "022-24107000",
            type: "Government / Municipal",
            category: "Apex Blood Center",
            lastUpdated: "5 mins ago",
            inventory: {
                "A+": { "Whole Blood": 15, "PRBC": 22, "FFP": 28, "RDP": 12, "SDP": 3, "Cryoprecipitate": 6 },
                "A-": { "Whole Blood": 3, "PRBC": 5, "FFP": 8, "RDP": 1, "SDP": 0, "Cryoprecipitate": 1 },
                "B+": { "Whole Blood": 24, "PRBC": 32, "FFP": 36, "RDP": 16, "SDP": 5, "Cryoprecipitate": 8 },
                "B-": { "Whole Blood": 2, "PRBC": 4, "FFP": 7, "RDP": 1, "SDP": 0, "Cryoprecipitate": 1 },
                "AB+": { "Whole Blood": 10, "PRBC": 15, "FFP": 20, "RDP": 6, "SDP": 2, "Cryoprecipitate": 4 },
                "AB-": { "Whole Blood": 1, "PRBC": 2, "FFP": 4, "RDP": 0, "SDP": 0, "Cryoprecipitate": 0 },
                "O+": { "Whole Blood": 28, "PRBC": 40, "FFP": 45, "RDP": 20, "SDP": 6, "Cryoprecipitate": 10 },
                "O-": { "Whole Blood": 4, "PRBC": 7, "FFP": 11, "RDP": 2, "SDP": 1, "Cryoprecipitate": 3 },
                "BOMBAY": { "Whole Blood": 2, "PRBC": 1, "FFP": 1, "RDP": 0, "SDP": 0, "Cryoprecipitate": 0 }
            }
        },
        {
            id: "BB-KA-01",
            name: "Victoria Hospital Blood Bank (BMCRI)",
            state: "Karnataka",
            district: "Bengaluru Urban",
            address: "Fort Road, Opp. City Market, Bengaluru - 560002",
            contact: "080-26701150",
            type: "Government Medical College",
            category: "Regional Blood Transfusion Center",
            lastUpdated: "18 mins ago",
            inventory: {
                "A+": { "Whole Blood": 16, "PRBC": 20, "FFP": 25, "RDP": 11, "SDP": 3, "Cryoprecipitate": 5 },
                "A-": { "Whole Blood": 2, "PRBC": 4, "FFP": 7, "RDP": 1, "SDP": 0, "Cryoprecipitate": 1 },
                "B+": { "Whole Blood": 21, "PRBC": 30, "FFP": 34, "RDP": 15, "SDP": 4, "Cryoprecipitate": 7 },
                "B-": { "Whole Blood": 3, "PRBC": 4, "FFP": 6, "RDP": 2, "SDP": 1, "Cryoprecipitate": 1 },
                "AB+": { "Whole Blood": 9, "PRBC": 14, "FFP": 18, "RDP": 7, "SDP": 2, "Cryoprecipitate": 3 },
                "AB-": { "Whole Blood": 1, "PRBC": 2, "FFP": 3, "RDP": 0, "SDP": 0, "Cryoprecipitate": 0 },
                "O+": { "Whole Blood": 26, "PRBC": 36, "FFP": 40, "RDP": 18, "SDP": 5, "Cryoprecipitate": 8 },
                "O-": { "Whole Blood": 4, "PRBC": 6, "FFP": 10, "RDP": 2, "SDP": 1, "Cryoprecipitate": 2 },
                "BOMBAY": { "Whole Blood": 0, "PRBC": 1, "FFP": 0, "RDP": 0, "SDP": 0, "Cryoprecipitate": 0 }
            }
        },
        {
            id: "BB-TN-01",
            name: "Rajiv Gandhi Government General Hospital",
            state: "Tamil Nadu",
            district: "Chennai",
            address: "EVR Periyar Salai, Park Town, Chennai - 600003",
            contact: "044-25305000",
            type: "Government",
            category: "State Apex Blood Bank",
            lastUpdated: "8 mins ago",
            inventory: {
                "A+": { "Whole Blood": 20, "PRBC": 26, "FFP": 32, "RDP": 14, "SDP": 4, "Cryoprecipitate": 7 },
                "A-": { "Whole Blood": 3, "PRBC": 5, "FFP": 9, "RDP": 2, "SDP": 1, "Cryoprecipitate": 1 },
                "B+": { "Whole Blood": 25, "PRBC": 38, "FFP": 42, "RDP": 19, "SDP": 6, "Cryoprecipitate": 9 },
                "B-": { "Whole Blood": 2, "PRBC": 4, "FFP": 7, "RDP": 1, "SDP": 0, "Cryoprecipitate": 1 },
                "AB+": { "Whole Blood": 11, "PRBC": 16, "FFP": 22, "RDP": 8, "SDP": 3, "Cryoprecipitate": 4 },
                "AB-": { "Whole Blood": 1, "PRBC": 3, "FFP": 5, "RDP": 1, "SDP": 0, "Cryoprecipitate": 0 },
                "O+": { "Whole Blood": 32, "PRBC": 48, "FFP": 54, "RDP": 24, "SDP": 7, "Cryoprecipitate": 11 },
                "O-": { "Whole Blood": 5, "PRBC": 8, "FFP": 12, "RDP": 3, "SDP": 2, "Cryoprecipitate": 3 },
                "BOMBAY": { "Whole Blood": 1, "PRBC": 1, "FFP": 1, "RDP": 0, "SDP": 0, "Cryoprecipitate": 0 }
            }
        }
    ],

    // 3. Voluntary Blood Donation Camps Schedule
    camps: [
        {
            id: "CAMP-2026-101",
            title: "Mega National Voluntary Blood Donation Drive",
            organizer: "Indian Red Cross Society & NSS AIIMS",
            state: "Delhi (NCT)",
            district: "New Delhi",
            venue: "AIIMS Jawaharlal Nehru Auditorium Campus",
            date: "2026-08-02",
            time: "09:00 AM - 05:00 PM",
            contact: "+91 98112 34567",
            targetUnits: 500,
            bookedSlots: 142
        },
        {
            id: "CAMP-2026-102",
            title: "Rotary Youth Voluntary Blood Donation Camp",
            organizer: "Rotary Club of Delhi Midtown & Lions Club",
            state: "Delhi (NCT)",
            district: "Central Delhi",
            venue: "Constitution Club of India, Rafi Marg",
            date: "2026-08-05",
            time: "10:00 AM - 04:00 PM",
            contact: "+91 98765 12345",
            targetUnits: 300,
            bookedSlots: 89
        },
        {
            id: "CAMP-2026-103",
            title: "Corporate Health & Blood Donation Drive",
            organizer: "Tech Mahindra Foundation & KEM Blood Bank",
            state: "Maharashtra",
            district: "Mumbai City",
            venue: "Tech Mahindra Tower Auditorium, Parel",
            date: "2026-08-03",
            time: "09:30 AM - 04:30 PM",
            contact: "+91 98200 99887",
            targetUnits: 250,
            bookedSlots: 110
        },
        {
            id: "CAMP-2026-104",
            title: "NSS University Blood Drive",
            organizer: "Bangalore University NSS Unit",
            state: "Karnataka",
            district: "Bengaluru Urban",
            venue: "Jnana Bharathi Campus Student Center",
            date: "2026-08-06",
            time: "09:00 AM - 03:00 PM",
            contact: "+91 94480 11223",
            targetUnits: 400,
            bookedSlots: 75
        }
    ],

    // 4. Blood Group Compatibility Rules
    compatibility: {
        "O-": {
            giveTo: ["O-", "O+", "A-", "A+", "B-", "B+", "AB-", "AB+"],
            receiveFrom: ["O-"],
            desc: "Universal Red Cell Donor. Extremely critical for emergency trauma surgeries."
        },
        "O+": {
            giveTo: ["O+", "A+", "B+", "AB+"],
            receiveFrom: ["O-", "O+"],
            desc: "Most common blood group in India (~38% of population)."
        },
        "A-": {
            giveTo: ["A-", "A+", "AB-", "AB+"],
            receiveFrom: ["O-", "A-"],
            desc: "Rare red cell donor group."
        },
        "A+": {
            giveTo: ["A+", "AB+"],
            receiveFrom: ["O-", "O+", "A-", "A+"],
            desc: "Second most common group in India."
        },
        "B-": {
            giveTo: ["B-", "B+", "AB-", "AB+"],
            receiveFrom: ["O-", "B-"],
            desc: "Rare group requiring regular voluntary donor registration."
        },
        "B+": {
            giveTo: ["B+", "AB+"],
            receiveFrom: ["O-", "O+", "B-", "B+"],
            desc: "Widespread group across South Asia (~32% of Indian population)."
        },
        "AB-": {
            giveTo: ["AB-", "AB+"],
            receiveFrom: ["O-", "A-", "B-", "AB-"],
            desc: "Rare blood group. Universal plasma donor."
        },
        "AB+": {
            giveTo: ["AB+"],
            receiveFrom: ["O-", "O+", "A-", "A+", "B-", "B+", "AB-", "AB+"],
            desc: "Universal Red Cell Recipient. Can receive red blood cells from any group."
        },
        "BOMBAY": {
            giveTo: ["BOMBAY", "O-", "O+", "A-", "A+", "B-", "B+", "AB-", "AB+"],
            receiveFrom: ["BOMBAY"],
            desc: "Extremely rare phenotype (hh). Can only receive blood from another Bombay Blood donor."
        }
    },

    // 5. Multi-Language Translations Dictionary
    translations: {
        en: {
            lang_name: "English",
            emergency_helpline_tag: "NATIONAL BLOOD HELPLINE",
            emergency_marquee: "Toll-Free Emergency Number: <strong>104</strong> / <strong>1075</strong> | Thalassemia & Rare Blood Group Urgent Assistance Desk Active 24x7 | Donate Blood, Save Lives!",
            btn_emergency_sos: "Emergency SOS Request",
            brand_subtitle: "Centralized Blood Center Management System • Govt. of India",
            nav_stock: "Blood Stock",
            nav_camps: "Donation Camps",
            nav_donor: "Register as Donor",
            nav_compatibility: "Compatibility",
            nav_admin: "Blood Bank Admin",
            hero_badge: "MoHFW & National Blood Transfusion Council Initiative",
            hero_title: "Connecting Life Savers With Every Urgent Need",
            hero_desc: "Real-time transparency for over 4,500+ registered blood banks across India. Search stock availability, book voluntary donation slots, or dispatch emergency requests in seconds.",
            hero_btn_stock: "Search Blood Stock",
            hero_btn_camps: "Find Nearby Camps",
            stat_blood_banks_label: "Registered Blood Banks",
            stat_available_units_label: "Units Currently Available",
            stat_camps_label: "Donation Camps Conducted",
            stat_donors_label: "Voluntary Registered Donors",
            tab1_title: "Real-Time Blood Stock Availability Search",
            tab1_desc: "Filter verified stock levels across licensed blood banks in your district.",
            tab1_syncing: "Live Data Syncing",
            label_state: "State / Union Territory",
            select_state_default: "-- Select State --",
            label_district: "District",
            select_district_default: "-- Select District --",
            label_blood_group: "Blood Group",
            all_groups: "All Groups",
            label_component: "Component Type",
            all_components: "All Components",
            btn_search_stock: "Search Stock",
            btn_reset: "Reset",
            found_prefix: "Found",
            found_suffix: "Blood Centers matching criteria",
            legend_in_stock: "In Stock (>10)",
            legend_low_stock: "Low Stock (3-10)",
            legend_critical: "Critical (<3)",
            no_centers_title: "No Licensed Blood Centers Found",
            no_centers_desc: "Try broadening your state, district, or component filters.",
            btn_contact_center: "Contact Center",
            tab2_title: "Upcoming Voluntary Blood Donation Camps",
            tab2_desc: "Locate mobile blood donation drives, campus camps, and community blood collection sessions near you.",
            label_filter_state: "Filter State",
            all_states: "All States",
            label_filter_date: "Filter Date",
            label_search_keyword: "Search Keyword",
            placeholder_keyword: "e.g. AIIMS, Red Cross, Rotary...",
            camp_organizer_label: "Organizer:",
            camp_slots_booked: "Slots Booked",
            btn_book_slot: "Book Donation Slot",
            badge_slot_confirmed: "Slot Confirmed",
            tab3_title: "Voluntary Donor Registration",
            tab3_desc: "Become part of India's centralized voluntary blood donor database.",
            label_full_name: "Full Name *",
            label_age: "Age (Years) *",
            label_gender: "Gender *",
            select_gender_default: "-- Select --",
            gender_male: "Male",
            gender_female: "Female",
            gender_trans: "Transgender",
            label_mobile: "Mobile Number *",
            label_email: "Email Address",
            label_weight: "Weight (kg) *",
            label_last_donated: "Date of Last Donation (Leave blank if First Time)",
            donor_consent_text: "I consent to receive urgent blood request notifications in case of emergency needs in my district.",
            btn_register_donor: "Register & Generate Digital Donor Pass",
            eligibility_title: "Am I Eligible To Donate Today?",
            eligibility_1: "Age between 18 and 65 years",
            eligibility_2: "Weight above 45 kg",
            eligibility_3: "Hemoglobin level ≥ 12.5 g/dL",
            eligibility_4: "Last donation was at least 90 days ago (for Whole Blood)",
            eligibility_5: "No active fever, infection, or ongoing antibiotic treatment",
            eligibility_6: "No major surgery in past 6 months",
            donor_card_title: "e-RaktKosh Voluntary Donor Card",
            donor_card_sub: "Government of India • Ministry of Health",
            donor_card_id: "Donor ID:",
            donor_card_mobile: "Mobile:",
            donor_card_state: "State:",
            donor_card_status: "Status:",
            donor_card_active_badge: "Active Lifesaver",
            donor_card_scan: "Scan at Blood Center",
            tab4_title: "Interactive Blood Group & Component Compatibility Guide",
            tab4_desc: "Select any blood group to highlight eligible donors and recipient matches instantly.",
            label_target_group: "Select Target Blood Group to inspect:",
            give_to_title: "Can GIVE Red Blood Cells To:",
            receive_from_title: "Can RECEIVE Red Blood Cells From:",
            shelf_life_title: "Blood Components & Shelf Life Guide",
            shelf_wb: "Whole Blood",
            shelf_wb_days: "35 - 42 Days",
            shelf_wb_desc: "Stored at 2°C to 6°C",
            shelf_prbc: "Packed Red Cells (PRBC)",
            shelf_prbc_days: "42 Days",
            shelf_prbc_desc: "Increases oxygen transport capacity",
            shelf_platelets: "Platelets (SDP / RDP)",
            shelf_platelets_days: "5 Days",
            shelf_platelets_desc: "Continuous agitation at 20°C - 24°C",
            shelf_ffp: "Fresh Frozen Plasma (FFP)",
            shelf_ffp_days: "1 Year",
            shelf_ffp_desc: "Frozen at -30°C or colder",
            tab5_title: "Blood Center Management & Inventory Control",
            tab5_desc: "Internal dashboard for blood bank operators, stock aging monitors, and emergency dispatch.",
            label_select_center: "Select Blood Center:",
            admin_stat_total: "Total In-Stock Units",
            badge_optimal: "Optimal Inventory",
            admin_stat_expiring: "Expiring Within 7 Days",
            badge_action_req: "Action Required",
            admin_stat_pending: "Pending Emergency Requests",
            badge_high_priority: "High Priority",
            admin_stat_next_camp: "Next Camp Scheduled",
            badge_next_camp: "AIIMS Campus Drive",
            th_blood_group: "Blood Group",
            th_whole_blood: "Whole Blood",
            th_prbc: "PRBC",
            th_platelets: "Platelets (SDP/RDP)",
            th_ffp: "FFP",
            th_status: "Stock Status",
            th_actions: "Actions",
            btn_dispatch: "Dispatch SOS",
            btn_add_unit: "+ Add Unit",
            sos_modal_title: "Emergency Blood Requirement SOS",
            sos_modal_desc: "Broadcast urgent request to nearby blood banks and registered voluntary donors.",
            label_patient_name: "Patient Name *",
            label_units_required: "Units Required *",
            label_urgency: "Urgency Timeline *",
            label_hospital: "Hospital Name & Address *",
            label_contact_doctor: "Attendant / Doctor Name *",
            label_contact_mobile: "Contact Phone *",
            btn_cancel: "Cancel",
            btn_broadcast: "Broadcast Emergency SOS",
            booking_modal_title: "Book Donation Appointment",
            label_booking_donor_name: "Donor Name *",
            label_pref_slot: "Preferred Time Slot *",
            btn_confirm_slot: "Confirm Slot & Generate Pass",
            footer_brand_desc: "Centralized Blood Center Management System under National Health Mission, Ministry of Health & Family Welfare, Government of India.",
            footer_quick_portals: "Quick Portals",
            footer_stock_link: "Blood Stock Availability",
            footer_camps_link: "Voluntary Camps Directory",
            footer_donor_link: "Donor Registration Portal",
            footer_compat_link: "Blood Compatibility Guide",
            footer_admin_link: "Blood Bank Login",
            footer_helpdesk: "Helpdesk Support",
            footer_helpline: "Emergency Helpline:",
            footer_email: "Email:",
            footer_tech_cell: "C-DAC & MoHFW Technical Cell, India",
            footer_copy: "© 2026 e-RaktKosh • Ministry of Health and Family Welfare. All Rights Reserved.",
            footer_tagline: "Designed with High Precision & Emergency Accessibility",
            toast_lang_switched: "Language switched to"
        },
        hi: {
            lang_name: "हिंदी (Hindi)",
            emergency_helpline_tag: "राष्ट्रीय रक्त हेल्पलाइन",
            emergency_marquee: "टोल-फ्री आपातकालीन नंबर: <strong>104</strong> / <strong>1075</strong> | थैलेसीमिया और दुर्लभ रक्त समूह तत्काल सहायता डेस्क 24x7 सक्रिय | रक्तदान करें, जीवन बचाएं!",
            btn_emergency_sos: "आपातकालीन SOS अनुरोध",
            brand_subtitle: "केंद्रीकृत रक्त केंद्र प्रबंधन प्रणाली • भारत सरकार",
            nav_stock: "रक्त उपलब्धता",
            nav_camps: "रक्तदान शिविर",
            nav_donor: "रक्तदाता पंजीकरण",
            nav_compatibility: "रक्त अनुकूलता",
            nav_admin: "ब्लड बैंक एडमिन",
            hero_badge: "स्वास्थ्य एवं परिवार कल्याण मंत्रालय व एनबीटीसी पहल",
            hero_title: "जीवन रक्षकों को हर तत्काल आवश्यकता से जोड़ना",
            hero_desc: "भारत भर के 4,500+ पंजीकृत ब्लड बैंकों की वास्तविक समय स्थिति। रक्त उपलब्धता खोजें, स्वैच्छिक रक्तदान स्लॉट बुक करें, या सेकंडों में आपातकालीन अनुरोध भेजें।",
            hero_btn_stock: "रक्त उपलब्धता खोजें",
            hero_btn_camps: "निकटतम शिविर खोजें",
            stat_blood_banks_label: "पंजीकृत ब्लड बैंक",
            stat_available_units_label: "वर्तमान उपलब्ध यूनिट्स",
            stat_camps_label: "आयोजित रक्तदान शिविर",
            stat_donors_label: "पंजीकृत स्वैच्छिक रक्तदाता",
            tab1_title: "वास्तविक समय रक्त स्टॉक उपलब्धता खोज",
            tab1_desc: "अपने जिले के लाइसेंस प्राप्त ब्लड बैंकों में सत्यापित रक्त स्टॉक स्तर देखें।",
            tab1_syncing: "लाइव डेटा सिंकिंग",
            label_state: "राज्य / केंद्र शासित प्रदेश",
            select_state_default: "-- राज्य चुनें --",
            label_district: "ज़िला",
            select_district_default: "-- ज़िला चुनें --",
            label_blood_group: "रक्त समूह",
            all_groups: "सभी रक्त समूह",
            label_component: "रक्त घटक प्रकार",
            all_components: "सभी घटक",
            btn_search_stock: "स्टॉक खोजें",
            btn_reset: "रीसेट करें",
            found_prefix: "कुल",
            found_suffix: "ब्लड सेंटर मिले",
            legend_in_stock: "उपलब्ध (>10)",
            legend_low_stock: "कम स्टॉक (3-10)",
            legend_critical: "अत्यंत कम (<3)",
            no_centers_title: "कोई लाइसेंस प्राप्त ब्लड सेंटर नहीं मिला",
            no_centers_desc: "कृपया राज्य, ज़िला या घटक फ़िल्टर बदलकर पुनः प्रयास करें।",
            btn_contact_center: "संपर्क करें",
            tab2_title: "आगामी स्वैच्छिक रक्तदान शिविर",
            tab2_desc: "अपने नजदीकी मोबाइल रक्तदान अभियान, कॉलेज कैंप और सामुदायिक रक्त संग्रह सत्र खोजें।",
            label_filter_state: "राज्य फ़िल्टर",
            all_states: "सभी राज्य",
            label_filter_date: "दिनांक फ़िल्टर",
            label_search_keyword: "खोजें (कीवर्ड)",
            placeholder_keyword: "उदा. AIIMS, रेड क्रॉस, रोटरी...",
            camp_organizer_label: "आयोजक:",
            camp_slots_booked: "स्लॉट बुक",
            btn_book_slot: "रक्तदान स्लॉट बुक करें",
            badge_slot_confirmed: "स्लॉट कन्फ़र्म हुआ",
            tab3_title: "स्वैच्छिक रक्तदाता पंजीकरण",
            tab3_desc: "भारत के केंद्रीकृत स्वैच्छिक रक्तदाता डेटाबेस का हिस्सा बनें।",
            label_full_name: "पूरा नाम *",
            label_age: "आयु (वर्ष) *",
            label_gender: "लिंग *",
            select_gender_default: "-- चुनें --",
            gender_male: "पुरुष",
            gender_female: "महिला",
            gender_trans: "ट्रांसजेंडर",
            label_mobile: "मोबाइल नंबर *",
            label_email: "ईमेल पता",
            label_weight: "वजन (किग्रा) *",
            label_last_donated: "अंतिम रक्तदान की तिथि (पहली बार हो तो खाली छोड़ें)",
            donor_consent_text: "मैं अपने जिले में आपातकालीन आवश्यकता के समय तत्काल रक्त अनुरोध संदेश प्राप्त करने की सहमति देता/देती हूँ।",
            btn_register_donor: "पंजीकरण करें और डिजिटल डोनर पास पाएं",
            eligibility_title: "क्या मैं आज रक्तदान के लिए पात्र हूँ?",
            eligibility_1: "आयु 18 से 65 वर्ष के बीच",
            eligibility_2: "वजन 45 किग्रा से अधिक",
            eligibility_3: "हीमोग्लोबिन स्तर ≥ 12.5 g/dL",
            eligibility_4: "पिछला रक्तदान कम से कम 90 दिन पहले हुआ हो",
            eligibility_5: "कोई सक्रिय बुखार, संक्रमण या एंटीबायोटिक उपचार नहीं",
            eligibility_6: "पिछले 6 महीनों में कोई बड़ी सर्जरी नहीं",
            donor_card_title: "ई-रक्तकोश स्वैच्छिक डोनर कार्ड",
            donor_card_sub: "भारत सरकार • स्वास्थ्य मंत्रालय",
            donor_card_id: "डोनर आईडी:",
            donor_card_mobile: "मोबाइल:",
            donor_card_state: "राज्य:",
            donor_card_status: "स्थिति:",
            donor_card_active_badge: "सक्रिय जीवन रक्षक",
            donor_card_scan: "ब्लड सेंटर पर स्कैन करें",
            tab4_title: "इंटरएक्टिव रक्त समूह एवं घटक अनुकूलता गाइड",
            tab4_desc: "योग्य रक्तदाताओं और प्राप्तकर्ताओं के मिलान देखने के लिए किसी भी रक्त समूह का चयन करें।",
            label_target_group: "जांचने के लिए रक्त समूह चुनें:",
            give_to_title: "लाल रक्त कोशिकाएं इन्हें दे सकते हैं:",
            receive_from_title: "लाल रक्त कोशिकाएं इनसे ले सकते हैं:",
            shelf_life_title: "रक्त घटक एवं शेल्फ लाइफ गाइड",
            shelf_wb: "होल ब्लड (संपूर्ण रक्त)",
            shelf_wb_days: "35 - 42 दिन",
            shelf_wb_desc: "2°C से 6°C पर संग्रहीत",
            shelf_prbc: "पैक्ड रेड सेल्स (PRBC)",
            shelf_prbc_days: "42 दिन",
            shelf_prbc_desc: "ऑक्सीजन वहन क्षमता बढ़ाता है",
            shelf_platelets: "प्लेटलेट्स (SDP / RDP)",
            shelf_platelets_days: "5 दिन",
            shelf_platelets_desc: "20°C - 24°C पर निरंतर हलचल",
            shelf_ffp: "फ्रेश फ्रोजन प्लाज्मा (FFP)",
            shelf_ffp_days: "1 वर्ष",
            shelf_ffp_desc: "-30°C या उससे कम तापमान पर जमे हुए",
            tab5_title: "रक्त केंद्र प्रबंधन एवं इन्वेंटरी नियंत्रण",
            tab5_desc: "ब्लड बैंक संचालकों, स्टॉक मॉनिटरिंग और आपातकालीन प्रेषण हेतु आंतरिक डैशबोर्ड।",
            label_select_center: "ब्लड सेंटर चुनें:",
            admin_stat_total: "कुल उपलब्ध यूनिट्स",
            badge_optimal: "इष्टतम इन्वेंटरी",
            admin_stat_expiring: "7 दिनों में समाप्त होने वाली",
            badge_action_req: "कार्रवाई आवश्यक",
            admin_stat_pending: "लंबित आपातकालीन अनुरोध",
            badge_high_priority: "उच्च प्राथमिकता",
            admin_stat_next_camp: "अगला शिविर",
            badge_next_camp: "एम्स कैंपस ड्राइव",
            th_blood_group: "रक्त समूह",
            th_whole_blood: "होल ब्लड",
            th_prbc: "PRBC",
            th_platelets: "प्लेटलेट्स (SDP/RDP)",
            th_ffp: "FFP प्लाज्मा",
            th_status: "स्टॉक स्थिति",
            th_actions: "कार्रवाई",
            btn_dispatch: "SOS प्रेषित करें",
            btn_add_unit: "+ यूनिट जोड़ें",
            sos_modal_title: "आपातकालीन रक्त आवश्यकता SOS",
            sos_modal_desc: "नजदीकी ब्लड बैंकों और पंजीकृत स्वैच्छिक दाताओं को तत्काल अलर्ट भेजें।",
            label_patient_name: "मरीज का नाम *",
            label_units_required: "आवश्यक यूनिट्स *",
            label_urgency: "आवश्यकता की समयसीमा *",
            label_hospital: "अस्पताल का नाम व पता *",
            label_contact_doctor: "अटेंडेंट / डॉक्टर का नाम *",
            label_contact_mobile: "संपर्क फोन *",
            btn_cancel: "रद्द करें",
            btn_broadcast: "आपातकालीन SOS प्रसारित करें",
            booking_modal_title: "रक्तदान अपॉइंटमेंट बुक करें",
            label_booking_donor_name: "रक्तदाता का नाम *",
            label_pref_slot: "पसंदीदा समय स्लॉट *",
            btn_confirm_slot: "स्लॉट कन्फ़र्म करें व पास बनाएं",
            footer_brand_desc: "राष्ट्रीय स्वास्थ्य मिशन, स्वास्थ्य एवं परिवार कल्याण मंत्रालय, भारत सरकार के अंतर्गत केंद्रीकृत रक्त केंद्र प्रबंधन प्रणाली।",
            footer_quick_portals: "त्वरित पोर्टल",
            footer_stock_link: "रक्त स्टॉक उपलब्धता",
            footer_camps_link: "स्वैच्छिक रक्तदान शिविर",
            footer_donor_link: "रक्तदाता पंजीकरण पोर्टल",
            footer_compat_link: "रक्त अनुकूलता गाइड",
            footer_admin_link: "ब्लड बैंक लॉगिन",
            footer_helpdesk: "हेल्पडेस्क सहायता",
            footer_helpline: "आपातकालीन हेल्पलाइन:",
            footer_email: "ईमेल:",
            footer_tech_cell: "सी-डैक और स्वास्थ्य मंत्रालय तकनीकी प्रकोष्ठ",
            footer_copy: "© 2026 ई-रक्तकोश • स्वास्थ्य एवं परिवार कल्याण मंत्रालय। सर्वाधिकार सुरक्षित।",
            footer_tagline: "उच्च सटीकता और आपातकालीन पहुंच के साथ निर्मित",
            toast_lang_switched: "भाषा बदल दी गई है:"
        },
        bn: {
            lang_name: "বাংলা (Bengali)",
            emergency_helpline_tag: "জাতীয় রক্ত ​​হেল্পলাইন",
            emergency_marquee: "টোল-ফ্রি জরুরি নম্বর: <strong>104</strong> / <strong>1075</strong> | থ্যালাসেমিয়া ও বিরল রক্তের গ্রুপের জরুরি সহায়তা ডেস্ক ২৪x৭ সক্রিয় | রক্ত দিন, জীবন বাঁচান!",
            btn_emergency_sos: "জরুরি SOS অনুরোধ",
            brand_subtitle: "কেন্দ্রীভূত রক্ত ​​কেন্দ্র পরিচালন ব্যবস্থা • ভারত সরকার",
            nav_stock: "রক্তের স্টক",
            nav_camps: "রক্তদান শিবির",
            nav_donor: "রক্তদাতা নিবন্ধন",
            nav_compatibility: "সামঞ্জস্যতা",
            nav_admin: "ব্লাড ব্যাংক অ্যাডমিন",
            hero_badge: "স্বাস্থ্য ও পরিবার কল্যাণ মন্ত্রকের উদ্যোগ",
            hero_title: "প্রতিটি জরুরি প্রয়োজনে জীবন রক্ষাকারীদের সাথে সংযোগ",
            hero_desc: "ভারত জুড়ে ৪,৫০০+ নিবন্ধিত ব্লাড ব্যাংকের রিয়েল-টাইম তথ্য। রক্তের প্রাপ্যতা খুঁজুন, স্বেচ্ছায় রক্তদানের স্লট বুক করুন, বা জরুরি অনুরোধ পাঠান।",
            hero_btn_stock: "রক্তের স্টক অনুসন্ধান",
            hero_btn_camps: "কাছাকাছি শিবির খুঁজুন",
            stat_blood_banks_label: "নিবন্ধিত ব্লাড ব্যাংক",
            stat_available_units_label: "বর্তমানে উপলব্ধ ইউনিট",
            stat_camps_label: "পরিচালিত রক্তদান শিবির",
            stat_donors_label: "নিবন্ধিত স্বেচ্ছাসেবী রক্তদাতা",
            tab1_title: "রিয়েল-টাইম রক্তের স্টক অনুসন্ধান",
            tab1_desc: "আপনার জেলার লাইসেন্সপ্রাপ্ত ব্লাড ব্যাংকগুলির যাচাইকৃত রক্তের স্টক দেখুন।",
            tab1_syncing: "লাইভ ডেটা সিঙ্ক হচ্ছে",
            label_state: "রাজ্য / কেন্দ্রশাসিত অঞ্চল",
            select_state_default: "-- রাজ্য নির্বাচন করুন --",
            label_district: "জেলা",
            select_district_default: "-- জেলা নির্বাচন করুন --",
            label_blood_group: "রক্তের গ্রুপ",
            all_groups: "সমস্ত রক্তের গ্রুপ",
            label_component: "উপাদানের ধরন",
            all_components: "সমস্ত উপাদান",
            btn_search_stock: "স্টক খুঁজুন",
            btn_reset: "রিসেট",
            found_prefix: "মোট",
            found_suffix: "টি ব্লাড সেন্টার পাওয়া গেছে",
            legend_in_stock: "স্টকে আছে (>১০)",
            legend_low_stock: "কম স্টক (৩-১০)",
            legend_critical: "জরুরি সংকট (<৩)",
            no_centers_title: "কোনো লাইসেন্সপ্রাপ্ত ব্লাড সেন্টার পাওয়া যায়নি",
            no_centers_desc: "অনুগ্রহ করে আপনার রাজ্য, জেলা বা উপাদানের ফিল্টার পরিবর্তন করুন।",
            btn_contact_center: "যোগাযোগ করুন",
            tab2_title: "আসন্ন স্বেচ্ছায় রক্তদান শিবির",
            tab2_desc: "আপনার কাছাকাছি মোবাইল রক্তদান অভিযান ও ক্যাম্প খুঁজুন।",
            label_filter_state: "রাজ্য ফিল্টার",
            all_states: "সমস্ত রাজ্য",
            label_filter_date: "তারিখ ফিল্টার",
            label_search_keyword: "অনুসন্ধান",
            placeholder_keyword: "উদাঃ AIIMS, রেড ক্রস...",
            camp_organizer_label: "আয়োজক:",
            camp_slots_booked: "স্লট বুক হয়েছে",
            btn_book_slot: "রক্তদানের স্লট বুক করুন",
            badge_slot_confirmed: "স্লট নিশ্চিত",
            tab3_title: "স্বেচ্ছাসেবী রক্তদাতা নিবন্ধন",
            tab3_desc: "ভারতের কেন্দ্রীভূত রক্তদাতা ডাটাবেসের অংশ হন।",
            label_full_name: "সম্পূর্ণ নাম *",
            label_age: "বয়স (বছর) *",
            label_gender: "লিঙ্গ *",
            select_gender_default: "-- নির্বাচন করুন --",
            gender_male: "পুরুষ",
            gender_female: "মহিলা",
            gender_trans: "রূপান্তরকামী",
            label_mobile: "মোবাইল নম্বর *",
            label_email: "ইমেল ঠিকানা",
            label_weight: "ওজন (কেজি) *",
            label_last_donated: "সর্বশেষ রক্তদানের তারিখ",
            donor_consent_text: "আমি আমার জেলায় জরুরি রক্তের প্রয়োজনের বিজ্ঞপ্তি পেতে সম্মত।",
            btn_register_donor: "নিবন্ধন করুন এবং ডিজিটাল পাস পান",
            eligibility_title: "আমি কি আজ রক্তদানের যোগ্য?",
            eligibility_1: "বয়স ১৮ থেকে ৬৫ বছরের মধ্যে",
            eligibility_2: "ওজন ৪৫ কেজির বেশি",
            eligibility_3: "হিমোগ্লোবিন স্তর ≥ ১২.৫ g/dL",
            eligibility_4: "শেষ রক্তদান কমপক্ষে ৯০ দিন আগে হয়েছে",
            eligibility_5: "কোনো জ্বর বা সক্রিয় সংক্রমণ নেই",
            eligibility_6: "গত ৬ মাসে কোনো বড় অস্ত্রোপচার হয়নি",
            donor_card_title: "ই-রক্তকোষ স্বেচ্ছাসেবী ডোনার কার্ড",
            donor_card_sub: "ভারত সরকার • স্বাস্থ্য মন্ত্রক",
            donor_card_id: "ডোনার আইডি:",
            donor_card_mobile: "মোবাইল:",
            donor_card_state: "রাজ্য:",
            donor_card_status: "অবস্থা:",
            donor_card_active_badge: "সক্রিয় জীবন রক্ষাকারী",
            donor_card_scan: "ব্লাড সেন্টারে স্ক্যান করুন",
            tab4_title: "রক্তের গ্রুপ ও উপাদান সামঞ্জস্যতা নির্দেশিকা",
            tab4_desc: "উপযুক্ত দাতা এবং প্রাপকদের তালিকা দেখতে রক্তের গ্রুপ নির্বাচন করুন।",
            label_target_group: "রক্তের গ্রুপ নির্বাচন করুন:",
            give_to_title: "লোহিত রক্তকণিকা দিতে পারেন:",
            receive_from_title: "লোহিত রক্তকণিকা নিতে পারেন:",
            shelf_life_title: "রক্তের উপাদান ও মেয়াদ নির্দেশিকা",
            shelf_wb: "হোল ব্লাড (সম্পূর্ণ রক্ত)",
            shelf_wb_days: "৩৫ - ৪২ দিন",
            shelf_wb_desc: "২°C থেকে ৬°C তাপমাত্রায় সংরক্ষিত",
            shelf_prbc: "প্যাকড রেড সেলস (PRBC)",
            shelf_prbc_days: "৪২ দিন",
            shelf_prbc_desc: "অক্সিজেন পরিবহন ক্ষমতা বৃদ্ধি করে",
            shelf_platelets: "প্লেটলেট (SDP / RDP)",
            shelf_platelets_days: "৫ দিন",
            shelf_platelets_desc: "২০°C - ২৪°C তাপমাত্রায় সার্বক্ষণিক আলোড়ন",
            shelf_ffp: "ফ্রেশ ফ্রোজেন প্লাজমা (FFP)",
            shelf_ffp_days: "১ বছর",
            shelf_ffp_desc: "-৩০°C বা তার নিচে হিমায়িত",
            tab5_title: "ব্লাড সেন্টার পরিচালন ও ইনভেন্টরি ড্যাশবোর্ড",
            tab5_desc: "ব্লাড ব্যাংক অপারেটর এবং স্টক মনিটরিংয়ের জন্য অভ্যন্তরীণ ড্যাশবোর্ড।",
            label_select_center: "ব্লাড সেন্টার নির্বাচন করুন:",
            admin_stat_total: "মোট উপলব্ধ ইউনিট",
            badge_optimal: "অনুকূল স্টক",
            admin_stat_expiring: "৭ দিনের মধ্যে মেয়াদ শেষ হবে",
            badge_action_req: "পদক্ষেপ প্রয়োজন",
            admin_stat_pending: "অমীমাংসিত জরুরি অনুরোধ",
            badge_high_priority: "উচ্চ অগ্রাধিকার",
            admin_stat_next_camp: "পরবর্তী নির্ধারিত শিবির",
            badge_next_camp: "AIIMS ক্যাম্পাস ড্রাইভ",
            th_blood_group: "রক্তের গ্রুপ",
            th_whole_blood: "হোল ব্লাড",
            th_prbc: "PRBC",
            th_platelets: "প্লেটলেট",
            th_ffp: "FFP প্লাজমা",
            th_status: "স্টক অবস্থা",
            th_actions: "পদক্ষেপ",
            btn_dispatch: "SOS পাঠান",
            btn_add_unit: "+ ইউনিট যোগ করুন",
            sos_modal_title: "জরুরি রক্তের প্রয়োজন SOS",
            sos_modal_desc: "কাছাকাছি ব্লাড ব্যাংক এবং নিবন্ধিত দাতাদের কাছে জরুরি বার্তা পাঠান।",
            label_patient_name: "রোগীর নাম *",
            label_units_required: "প্রয়োজনীয় ইউনিট *",
            label_urgency: "জরুরিতা সময়সীমা *",
            label_hospital: "হাসপাতালের নাম ও ঠিকানা *",
            label_contact_doctor: "অ্যাটেনডেন্ট / চিকিৎসকের নাম *",
            label_contact_mobile: "যোগাযোগের ফোন *",
            btn_cancel: "বাতিল করুন",
            btn_broadcast: "জরুরি SOS সম্প্রচার করুন",
            booking_modal_title: "রক্তদানের অ্যাপয়েন্টমেন্ট বুক করুন",
            label_booking_donor_name: "রক্তদাতার নাম *",
            label_pref_slot: "পছন্দের সময় স্লট *",
            btn_confirm_slot: "স্লট নিশ্চিত করুন ও পাস পান",
            footer_brand_desc: "জাতীয় স্বাস্থ্য মিশন, স্বাস্থ্য ও পরিবার কল্যাণ মন্ত্রক, ভারত সরকারের অধীনে কেন্দ্রীভূত রক্ত ​​কেন্দ্র পরিচালন ব্যবস্থা।",
            footer_quick_portals: "দ্রুত পোর্টাল",
            footer_stock_link: "রক্তের স্টক প্রাপ্যতা",
            footer_camps_link: "স্বেচ্ছায় রক্তদান শিবির",
            footer_donor_link: "রক্তদাতা নিবন্ধন পোর্টাল",
            footer_compat_link: "রক্তের সামঞ্জস্যতা নির্দেশিকা",
            footer_admin_link: "ব্লাড ব্যাংক লগইন",
            footer_helpdesk: "হেল্পডেস্ক সহায়তা",
            footer_helpline: "জরুরি হেল্পলাইন:",
            footer_email: "ইমেল:",
            footer_tech_cell: "C-DAC এবং স্বাস্থ্য মন্ত্রক কারিগরি সেল",
            footer_copy: "© ২০২৬ ই-রক্তকোষ • স্বাস্থ্য ও পরিবার কল্যাণ মন্ত্রক। সর্বস্বত্ব সংরক্ষিত।",
            footer_tagline: "উচ্চ নির্ভুলতা এবং জরুরি অ্যাক্সেসিবিলিটি সহ নির্মিত",
            toast_lang_switched: "ভাষা পরিবর্তন করা হয়েছে:"
        },
        ta: {
            lang_name: "தமிழ் (Tamil)",
            emergency_helpline_tag: "தேசிய இரத்த உதவி எண்",
            emergency_marquee: "இலவச அவசர உதவி எண்: <strong>104</strong> / <strong>1075</strong> | தலசீமியா மற்றும் அரிய இரத்த வகை அவசர உதவி மையம் 24x7 செயல்படுகிறது | இரத்தம் தானம் செய்வோம், உயிர் காப்போம்!",
            btn_emergency_sos: "அவசர SOS கோரிக்கை",
            brand_subtitle: "மத்திய இரத்த வங்கி மேலாண்மை அமைப்பு • இந்திய அரசு",
            nav_stock: "இரத்த இருப்பு",
            nav_camps: "இரத்ததான முகாம்கள்",
            nav_donor: "நன்கொடையாளர் பதிவு",
            nav_compatibility: "இரத்தப் பொருத்தம்",
            nav_admin: "இரத்த வங்கி நிர்வாகம்",
            hero_badge: "சுகாதாரம் மற்றும் குடும்ப நல அமைச்சகத்தின் முன்முயற்சி",
            hero_title: "ஒவ்வொரு அவசரத் தேவைக்கும் உயிர்காப்பாளர்களை இணைக்கிறது",
            hero_desc: "இந்தியா முழுவதும் உள்ள 4,500+ பதிவுசெய்யப்பட்ட இரத்த வங்கிகளின் நேரடி இருப்பு விவரங்கள். இருப்பை அறியவும், முகாம் முன்பதிவு செய்யவும் அல்லது அவசர கோரிக்கை அனுப்பவும்.",
            hero_btn_stock: "இரத்த இருப்பைத் தேடுக",
            hero_btn_camps: "அருகிலுள்ள முகாம்களைக் காண்க",
            stat_blood_banks_label: "பதிவுசெய்த இரத்த வங்கிகள்",
            stat_available_units_label: "தற்போது கிடைக்கும் அலகுகள்",
            stat_camps_label: "நடத்தப்பட்ட இரத்ததான முகாம்கள்",
            stat_donors_label: "பதிவுசெய்த இரத்த தான நன்கொடையாளர்கள்",
            tab1_title: "நேரலை இரத்த இருப்பு தேடல்",
            tab1_desc: "உங்கள் மாவட்டத்தில் உள்ள அங்கீகரிக்கப்பட்ட இரத்த வங்கிகளில் சரிபார்க்கப்பட்ட இருப்பைக் காண்க.",
            tab1_syncing: "நேரலை தரவு புதுப்பிப்பு",
            label_state: "மாநிலம் / யூனியன் பிரதேசம்",
            select_state_default: "-- மாநிலத்தைத் தேர்ந்தெடுக்கவும் --",
            label_district: "மாவட்டம்",
            select_district_default: "-- மாவட்டத்தைத் தேர்ந்தெடுக்கவும் --",
            label_blood_group: "இரத்த வகை",
            all_groups: "அனைத்து இரத்த வகைகள்",
            label_component: "கூறு வகை",
            all_components: "அனைத்து கூறுகள்",
            btn_search_stock: "இருப்பைத் தேடுக",
            btn_reset: "மீட்டமை",
            found_prefix: "மொத்தம்",
            found_suffix: "இரத்த மையங்கள் கண்டறியப்பட்டன",
            legend_in_stock: "இருப்பில் உள்ளது (>10)",
            legend_low_stock: "குறைந்த இருப்பு (3-10)",
            legend_critical: "மிகக் குறைந்த இருப்பு (<3)",
            no_centers_title: "இரத்த மையங்கள் எதுவும் கிடைக்கவில்லை",
            no_centers_desc: "உங்கள் மாநிலம், மாவட்டம் அல்லது கூறு வடிகட்டிகளை மாற்றி மீண்டும் முயற்சிக்கவும்.",
            btn_contact_center: "தொடர்பு கொள்ள",
            tab2_title: "வரவிருக்கும் தன்னார்வ இரத்ததான முகாம்கள்",
            tab2_desc: "உங்கள் அருகில் நடைபெறும் இரத்ததான முகாம்களைக் கண்டறியவும்.",
            label_filter_state: "மாநில வடிகட்டி",
            all_states: "அனைத்து மாநிலங்கள்",
            label_filter_date: "தேதி வடிகட்டி",
            label_search_keyword: "தேடல் சொல்",
            placeholder_keyword: "எ.கா. AIIMS, ரெட் கிராஸ்...",
            camp_organizer_label: "அமைப்பாளர்:",
            camp_slots_booked: "முன்பதிவு செய்யப்பட்ட இடங்கள்",
            btn_book_slot: "முன்பதிவு செய்க",
            badge_slot_confirmed: "முன்பதிவு உறுதி செய்யப்பட்டது",
            tab3_title: "தன்னார்வ நன்கொடையாளர் பதிவு",
            tab3_desc: "இந்தியாவின் மத்திய இரத்த தான நன்கொடையாளர் தரவுத்தளத்தில் இணையுங்கள்.",
            label_full_name: "முழு பெயர் *",
            label_age: "வயது (ஆண்டுகள்) *",
            label_gender: "பாலினம் *",
            select_gender_default: "-- தேர்ந்தெடுக்கவும் --",
            gender_male: "ஆண்",
            gender_female: "பெண்",
            gender_trans: "திருநங்கை / திருநம்பி",
            label_mobile: "கைபேசி எண் *",
            label_email: "மின்னஞ்சல் முகவரி",
            label_weight: "எடை (கிலோ) *",
            label_last_donated: "கடைசி இரத்ததான தேதி",
            donor_consent_text: "என் மாவட்டத்தில் அவசர தேவை ஏற்படும்போது அறிவிப்புகளைப் பெற ஒப்புக்கொள்கிறேன்.",
            btn_register_donor: "பதிவு செய்து டிஜிட்டல் பாஸ் பெறுக",
            eligibility_title: "இன்று நான் இரத்த தானம் செய்ய தகுதியானவரா?",
            eligibility_1: "வயது 18 முதல் 65 வரை",
            eligibility_2: "எடை 45 கிலோவுக்கு மேல்",
            eligibility_3: "ஹீமோகுளோபின் அளவு ≥ 12.5 g/dL",
            eligibility_4: "கடைசி தானம் குறைந்தது 90 நாட்களுக்கு முன் இருக்க வேண்டும்",
            eligibility_5: "காய்ச்சல் அல்லது தீவிர தொற்று இருக்கக்கூடாது",
            eligibility_6: "கடந்த 6 மாதங்களில் பெரிய அறுவை சிகிச்சை இல்லை",
            donor_card_title: "இ-ரக்த்கோஷ் தன்னார்வ நன்கொடையாளர் அட்டை",
            donor_card_sub: "இந்திய அரசு • சுகாதார அமைச்சகம்",
            donor_card_id: "நன்கொடையாளர் எண்:",
            donor_card_mobile: "கைபேசி:",
            donor_card_state: "மாநிலம்:",
            donor_card_status: "நிலை:",
            donor_card_active_badge: "உயிர் காப்பாளர்",
            donor_card_scan: "இரத்த மையத்தில் ஸ்கேன் செய்க",
            tab4_title: "இரத்த வகை மற்றும் கூறு பொருத்தம் வழிகாட்டி",
            tab4_desc: "பொருத்தமான நன்கொடையாளர்கள் மற்றும் பெறுநர்களைக் காண இரத்த வகையைத் தேர்ந்தெடுக்கவும்.",
            label_target_group: "ஆராய இரத்த வகையைத் தேர்ந்தெடுக்கவும்:",
            give_to_title: "சிவப்பணுக்களை வழங்கக்கூடிய இரத்த வகைகள்:",
            receive_from_title: "சிவப்பணுக்களைப் பெறக்கூடிய இரத்த வகைகள்:",
            shelf_life_title: "இரத்தக் கூறுகள் மற்றும் ஆயுட்காலம் வழிகாட்டி",
            shelf_wb: "முழு இரத்தம் (Whole Blood)",
            shelf_wb_days: "35 - 42 நாட்கள்",
            shelf_wb_desc: "2°C முதல் 6°C வரை சேமிக்கப்படுகிறது",
            shelf_prbc: "செறிவூட்டப்பட்ட சிவப்பணுக்கள் (PRBC)",
            shelf_prbc_days: "42 நாட்கள்",
            shelf_prbc_desc: "ஆக்ஸிஜன் கொண்டு செல்லும் திறனை அதிகரிக்கிறது",
            shelf_platelets: "பிளேட்லெட்டுகள் (SDP / RDP)",
            shelf_platelets_days: "5 நாட்கள்",
            shelf_platelets_desc: "20°C - 24°C-ல் தொடர்ச்சியான அசைவு",
            shelf_ffp: "உறைந்த பிளாஸ்மா (FFP)",
            shelf_ffp_days: "1 வருடம்",
            shelf_ffp_desc: "-30°C அல்லது அதற்கும் கீழ் உறைய வைக்கப்படுகிறது",
            tab5_title: "இரத்த மையம் மற்றும் இருப்பு மேலாண்மை",
            tab5_desc: "இரத்த வங்கி ஆபரேட்டர்கள் மற்றும் அவசர அனுப்புதலுக்கான உள் கட்டுப்பாட்டு பலகம்.",
            label_select_center: "இரத்த மையத்தைத் தேர்ந்தெடுக்கவும்:",
            admin_stat_total: "மொத்த இருப்பு அலகுகள்",
            badge_optimal: "போதுமான இருப்பு",
            admin_stat_expiring: "7 நாட்களில் காலாவதியாகும் அலகுகள்",
            badge_action_req: "நடவடிக்கை தேவை",
            admin_stat_pending: "நிலுவையில் உள்ள அவசர கோரிக்கைகள்",
            badge_high_priority: "உயர் முன்னுரிமை",
            admin_stat_next_camp: "அடுத்த முகாம்",
            badge_next_camp: "AIIMS வளாக முகாம்",
            th_blood_group: "இரத்த வகை",
            th_whole_blood: "முழு இரத்தம்",
            th_prbc: "PRBC",
            th_platelets: "பிளேட்லெட்டுகள்",
            th_ffp: "FFP பிளாஸ்மா",
            th_status: "இருப்பு நிலை",
            th_actions: "செயல்கள்",
            btn_dispatch: "SOS அனுப்புக",
            btn_add_unit: "+ அலகு சேர்",
            sos_modal_title: "அவசர இரத்தத் தேவை SOS",
            sos_modal_desc: "அருகிலுள்ள இரத்த வங்கிகள் மற்றும் நன்கொடையாளர்களுக்கு அவசர எச்சரிக்கை அனுப்பவும்.",
            label_patient_name: "நோயாளி பெயர் *",
            label_units_required: "தேவைப்படும் அலகுகள் *",
            label_urgency: "அவசர கால வரம்பு *",
            label_hospital: "மருத்துவமனை பெயர் & முகவரி *",
            label_contact_doctor: "உதவியாளர் / மருத்துவர் பெயர் *",
            label_contact_mobile: "தொடர்பு தொலைபேசி *",
            btn_cancel: "ரத்து செய்",
            btn_broadcast: "அவசர SOS அனுப்புக",
            booking_modal_title: "இரத்ததான முன்பதிவு செய்க",
            label_booking_donor_name: "நன்கொடையாளர் பெயர் *",
            label_pref_slot: "விருப்பமான நேர இடைவெளி *",
            btn_confirm_slot: "முன்பதிவு செய்து பாஸ் பெறுக",
            footer_brand_desc: "தேசிய சுகாதார இயக்கம், சுகாதாரம் மற்றும் குடும்ப நல அமைச்சகம், இந்திய அரசின் கீழ் செயல்படும் மத்திய இரத்த வங்கி மேலாண்மை அமைப்பு.",
            footer_quick_portals: "விரைவு இணையதளங்கள்",
            footer_stock_link: "இரத்த இருப்பு விவரம்",
            footer_camps_link: "தன்னார்வ முகாம்கள்",
            footer_donor_link: "நன்கொடையாளர் பதிவு",
            footer_compat_link: "இரத்தப் பொருத்த வழிகாட்டி",
            footer_admin_link: "இரத்த வங்கி உள்நுழைவு",
            footer_helpdesk: "உதவி மையம்",
            footer_helpline: "அவசர உதவி எண்:",
            footer_email: "மின்னஞ்சல்:",
            footer_tech_cell: "C-DAC மற்றும் சுகாதார அமைச்சக தொழில்நுட்பப் பிரிவு",
            footer_copy: "© 2026 இ-ரக்த்கோஷ் • சுகாதாரம் மற்றும் குடும்ப நல அமைச்சகம். அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.",
            footer_tagline: "அதிக துல்லியத்தன்மை மற்றும் அவசர அணுகலுடன் வடிவமைக்கப்பட்டது",
            toast_lang_switched: "மொழி மாற்றப்பட்டது:"
        },
        te: {
            lang_name: "తెలుగు (Telugu)",
            emergency_helpline_tag: "జాతీయ రక్త హెల్ప్‌లైన్",
            emergency_marquee: "టోల్-ఫ్రీ అత్యవసర నంబర్: <strong>104</strong> / <strong>1075</strong> | తలసేమియా & అరుదైన రక్త సమూహం అత్యవసర సహాయ డెస్క్ 24x7 యాక్టివ్ | రక్తం దానం చేయండి, ప్రాణాలను కాపాడండి!",
            btn_emergency_sos: "అత్యవసర SOS అభ్యర్థన",
            brand_subtitle: "కేంద్రీకృత బ్లడ్ బ్యాంక్ మేనేజ్‌మెంట్ సిస్టమ్ • భారత ప్రభుత్వం",
            nav_stock: "రక్త నిల్వలు",
            nav_camps: "రక్తదాన శిబిరాలు",
            nav_donor: "రక్తదాత నమోదు",
            nav_compatibility: "రక్త అనుకూలత",
            nav_admin: "బ్లడ్ బ్యాంక్ అడ్మిన్",
            hero_badge: "ఆరోగ్య & కుటుంబ సంక్షేమ మంత్రిత్వ శాఖ చొరవ",
            hero_title: "ప్రతి అత్యవసర అవసరానికి ప్రాణదాతలను అనుసంధానిస్తుంది",
            hero_desc: "భారతదేశం అంతటా 4,500+ రిజిస్టర్డ్ బ్లడ్ బ్యాంకుల రియల్-టైమ్ నిల్వ వివరాలు. లభ్యతను తనిఖీ చేయండి, రక్తదాన స్లాట్ బుక్ చేయండి లేదా అత్యవసర అభ్యర్థనలను పంపండి.",
            hero_btn_stock: "రక్త నిల్వలను శోధించండి",
            hero_btn_camps: "సమీప శిబిరాలను కనుగొనండి",
            stat_blood_banks_label: "రిజిస్టర్డ్ బ్లడ్ బ్యాంకులు",
            stat_available_units_label: "ప్రస్తుతం అందుబాటులో ఉన్న యూనిట్లు",
            stat_camps_label: "నిర్వహించిన రక్తదాన శిబిరాలు",
            stat_donors_label: "రిజిస్టర్డ్ స్వచ్ఛంద రక్తదాతలు",
            tab1_title: "రియల్-టైమ్ రక్త నిల్వల లభ్యత శోధన",
            tab1_desc: "మీ జిల్లాలోని లైసెన్స్ పొందిన బ్లడ్ బ్యాంకులలో ధృవీకరించబడిన నిల్వలను తనిఖీ చేయండి.",
            tab1_syncing: "లైవ్ డేటా సింక్ అవుతోంది",
            label_state: "రాష్ట్రం / కేంద్రపాలిత ప్రాంతం",
            select_state_default: "-- రాష్ట్రాన్ని ఎంచుకోండి --",
            label_district: "జిల్లా",
            select_district_default: "-- జిల్లాను ఎంచుకోండి --",
            label_blood_group: "రక్త సమూహం",
            all_groups: "అన్ని గ్రూపులు",
            label_component: "రక్త భాగం రకం",
            all_components: "అన్ని భాగాలు",
            btn_search_stock: "నిల్వలను శోధించండి",
            btn_reset: "రీసెట్ చేయండి",
            found_prefix: "మొత్తం",
            found_suffix: "బ్లడ్ సెంటర్లు కనుగొనబడ్డాయి",
            legend_in_stock: "అందుబాటులో ఉంది (>10)",
            legend_low_stock: "తక్కువ నిల్వ (3-10)",
            legend_critical: "చాలా తక్కువ (<3)",
            no_centers_title: "బ్లడ్ సెంటర్లు ఏవీ కనుగొనబడలేదు",
            no_centers_desc: "దయచేసి రాష్ట్రం, జిల్లా లేదా భాగం ఫిల్టర్లను మార్చండి.",
            btn_contact_center: "సంప్రదించండి",
            tab2_title: "రాబోయే స్వచ్ఛంద రక్తదాన శిబిరాలు",
            tab2_desc: "మీ సమీపంలోని మొబైల్ రక్తదాన శిబిరాలను కనుగొనండి.",
            label_filter_state: "రాష్ట్ర ఫిల్టర్",
            all_states: "అన్ని రాష్ట్రాలు",
            label_filter_date: "తేదీ ఫిల్టర్",
            label_search_keyword: "కీవర్డ్ శోధన",
            placeholder_keyword: "ఉదా. AIIMS, రెడ్ క్రాస్...",
            camp_organizer_label: "నిర్వాహకులు:",
            camp_slots_booked: "బుక్ చేసిన స్లాట్లు",
            btn_book_slot: "రక్తదాన స్లాట్ బుక్ చేయండి",
            badge_slot_confirmed: "స్లాట్ ఖరారైంది",
            tab3_title: "స్వచ్ఛంద రక్తదాత నమోదు",
            tab3_desc: "భారతదేశ కేంద్రీకృత రక్తదాతల డేటాబేస్‌లో భాగస్వామ్యం అవ్వండి.",
            label_full_name: "పూర్తి పేరు *",
            label_age: "వయస్సు (సంవత్సరాలు) *",
            label_gender: "లింగం *",
            select_gender_default: "-- ఎంచుకోండి --",
            gender_male: "పురుషుడు",
            gender_female: "స్త్రీ",
            gender_trans: "ట్రాన్స్‌జెండర్",
            label_mobile: "మొబైల్ నంబర్ *",
            label_email: "ఈమెయిల్ చిరునామా",
            label_weight: "బరువు (కిలోలు) *",
            label_last_donated: "చివరిసారి రక్తదానం చేసిన తేదీ",
            donor_consent_text: "నా జిల్లాలో అత్యవసర పరిస్థితుల్లో రక్త అభ్యర్థన నోటిఫికేషన్‌లను స్వీకరించడానికి నేను అంగీకరిస్తున్నాను.",
            btn_register_donor: "నమోదు చేసుకోండి & డిజిటల్ పాస్ పొందండి",
            eligibility_title: "నేను ఈరోజు రక్తదానం చేయడానికి అర్హుడనా?",
            eligibility_1: "వయస్సు 18 నుండి 65 సంవత్సరాల మధ్య",
            eligibility_2: "బరువు 45 కిలోల కంటే ఎక్కువ",
            eligibility_3: "హిమోగ్లోబిన్ స్థాయి ≥ 12.5 g/dL",
            eligibility_4: "చివరి దానం కనీసం 90 రోజుల క్రితం జరిగి ఉండాలి",
            eligibility_5: "ఎటువంటి జ్వరం లేదా ఇన్ఫెక్షన్ ఉండకూడదు",
            eligibility_6: "గత 6 నెలల్లో పెద్ద సర్జరీలు జరగలేదు",
            donor_card_title: "ఇ-రక్తకోష్ రక్తదాత కార్డు",
            donor_card_sub: "భారత ప్రభుత్వం • ఆరోగ్య మంత్రిత్వ శాఖ",
            donor_card_id: "డోనర్ ఐడీ:",
            donor_card_mobile: "మొబైల్:",
            donor_card_state: "రాష్ట్రం:",
            donor_card_status: "స్థితి:",
            donor_card_active_badge: "ప్రాణదాత",
            donor_card_scan: "బ్లడ్ సెంటర్‌లో స్కాన్ చేయండి",
            tab4_title: "రక్త సమూహ అనుకూలత గైడ్",
            tab4_desc: "తగిన దాతలు మరియు గ్రహీతల వివరాలను చూడటానికి రక్త గ్రూపును ఎంచుకోండి.",
            label_target_group: "రక్త సమూహాన్ని ఎంచుకోండి:",
            give_to_title: "ఎర్ర రక్త కణాలను వీరికి ఇవ్వవచ్చు:",
            receive_from_title: "ఎర్ర రక్త కణాలను వీరి నుండి స్వీకరించవచ్చు:",
            shelf_life_title: "రక్త భాగాలు మరియు నిల్వ కాల గైడ్",
            shelf_wb: "హోల్ బ్లడ్ (పూర్తి రక్తం)",
            shelf_wb_days: "35 - 42 రోజులు",
            shelf_wb_desc: "2°C నుండి 6°C వద్ద నిల్వ చేస్తారు",
            shelf_prbc: "ప్యాక్డ్ రెడ్ సెల్స్ (PRBC)",
            shelf_prbc_days: "42 రోజులు",
            shelf_prbc_desc: "ఆక్సిజన్ రవాణా సామర్థ్యాన్ని పెంచుతుంది",
            shelf_platelets: "ప్లేట్‌లెట్స్ (SDP / RDP)",
            shelf_platelets_days: "5 రోజులు",
            shelf_platelets_desc: "20°C - 24°C వద్ద నిరంతర కదలిక",
            shelf_ffp: "ఫ్రెష్ ఫ్రోజెన్ ప్లాస్మా (FFP)",
            shelf_ffp_days: "1 సంవత్సరం",
            shelf_ffp_desc: "-30°C లేదా అంతకంటే తక్కువ వద్ద నిల్వ",
            tab5_title: "బ్లడ్ సెంటర్ నిర్వహణ & ఇన్వెంటరీ",
            tab5_desc: "బ్లడ్ బ్యాంక్ ఆపరేటర్లు మరియు అత్యవసర సరఫరా కోసం అంతర్గత డ్యాష్‌బోర్డ్.",
            label_select_center: "బ్లడ్ సెంటర్‌ను ఎంచుకోండి:",
            admin_stat_total: "మొత్తం అందుబాటులో ఉన్న యూనిట్లు",
            badge_optimal: "సరిపడా నిల్వలు",
            admin_stat_expiring: "7 రోజుల్లో గడువు ముగిసేవి",
            badge_action_req: "చర్య అవసరం",
            admin_stat_pending: "పెండింగ్‌లో ఉన్న అత్యవసర అభ్యర్థనలు",
            badge_high_priority: "అత్యధిక ప్రాధాన్యత",
            admin_stat_next_camp: "తదుపరి శిబిరం",
            badge_next_camp: "AIIMS క్యాంపస్ డ్రైవ్",
            th_blood_group: "రక్త సమూహం",
            th_whole_blood: "హోల్ బ్లడ్",
            th_prbc: "PRBC",
            th_platelets: "ప్లేట్‌లెట్స్",
            th_ffp: "FFP ప్లాస్మా",
            th_status: "నిల్వ స్థితి",
            th_actions: "చర్యలు",
            btn_dispatch: "SOS పంపండి",
            btn_add_unit: "+ యూనిట్ జోడించండి",
            sos_modal_title: "అత్యవసర రక్త అవసరం SOS",
            sos_modal_desc: "సమీపంలోని బ్లడ్ బ్యాంకులు మరియు దాతలకు అత్యవసర హెచ్చరిక పంపండి.",
            label_patient_name: "రోగి పేరు *",
            label_units_required: "అవసరమైన యూనిట్లు *",
            label_urgency: "అత్యవసర కాలపరిమితి *",
            label_hospital: "ఆసుపత్రి పేరు & చిరునామా *",
            label_contact_doctor: "అటెండెంట్ / డాక్టర్ పేరు *",
            label_contact_mobile: "సంప్రదింపు ఫోన్ *",
            btn_cancel: "రద్దు చేయండి",
            btn_broadcast: "అత్యవసర SOS ప్రసారం చేయండి",
            booking_modal_title: "రక్తదాన అపాయింట్‌మెంట్ బుక్ చేయండి",
            label_booking_donor_name: "దాత పేరు *",
            label_pref_slot: "ప్రాధాన్య సమయ స్లాట్ *",
            btn_confirm_slot: "స్లాట్ ఖరారు చేసి పాస్ పొందండి",
            footer_brand_desc: "జాతీయ ఆరోగ్య మిషన్, ఆరోగ్య & కుటుంబ సంక్షేమ మంత్రిత్వ శాఖ, భారత ప్రభుత్వం ఆధ్వర్యంలో కేంద్రీకృత బ్లడ్ బ్యాంక్ మేనేజ్‌మెంట్ సిస్టమ్.",
            footer_quick_portals: "త్వరిత పోర్టల్స్",
            footer_stock_link: "రక్త నిల్వల లభ్యత",
            footer_camps_link: "రక్తదాన శిబిరాల డైరెక్టరీ",
            footer_donor_link: "రక్తదాత నమోదు పోర్టల్",
            footer_compat_link: "రక్త అనుకూలత గైడ్",
            footer_admin_link: "బ్లడ్ బ్యాంక్ లాగిన్",
            footer_helpdesk: "హెల్ప్‌డెస్క్ మద్దతు",
            footer_helpline: "అత్యవసర హెల్ప్‌లైన్:",
            footer_email: "ఈమెయిల్:",
            footer_tech_cell: "C-DAC & ఆరోగ్య మంత్రిత్వ శాఖ సాంకేతిక విభాగం",
            footer_copy: "© 2026 ఇ-రక్తకోష్ • ఆరోగ్య & కుటుంబ సంక్షేమ మంత్రిత్వ శాఖ. సర్వహక్కులు ప్రత్యేకించబడ్డాయి.",
            footer_tagline: "అత్యున్నత ఖచ్చితత్వం మరియు అత్యవసర సదుపాయంతో రూపొందించబడింది",
            toast_lang_switched: "భాష మార్చబడింది:"
        },
        mr: {
            lang_name: "मराठी (Marathi)",
            emergency_helpline_tag: "राष्ट्रीय रक्त हेल्पलाइन",
            emergency_marquee: "टोल-फ्री आपत्कालीन क्रमांक: <strong>104</strong> / <strong>1075</strong> | थॅलेसेमिया आणि दुर्मिळ रक्तगट तातडीची मदत डेस्क २४x७ कार्यरत | रक्तदान करा, जीवन वाचवा!",
            btn_emergency_sos: "आपत्कालीन SOS विनंती",
            brand_subtitle: "केंद्रीकृत रक्त केंद्र व्यवस्थापन प्रणाली • भारत सरकार",
            nav_stock: "रक्त साठा",
            nav_camps: "रक्तदान शिबिरे",
            nav_donor: "रक्तदाता नोंदणी",
            nav_compatibility: "रक्त सुसंगतता",
            nav_admin: "ब्लड बँक ॲडमिन",
            hero_badge: "आरोग्य व कुटुंब कल्याण मंत्रालय आणि एनबीटीसी उपक्रम",
            hero_title: "प्रत्येक तातडीच्या गरजेसाठी जीवनरक्षकांना जोडणे",
            hero_desc: "भारतभरातील ४,५००+ नोंदणीकृत रक्तपेढ्यांची रिअल-टाइम माहिती. रक्त उपलब्धता शोधा, ऐच्छिक रक्तदान स्लॉट बुक करा किंवा आपत्कालीन विनंत्या पाठवा.",
            hero_btn_stock: "रक्त साठा शोधा",
            hero_btn_camps: "जवळपासची शिबिरे शोधा",
            stat_blood_banks_label: "नोंदणीकृत रक्तपेढ्या",
            stat_available_units_label: "सध्या उपलब्ध युनिट्स",
            stat_camps_label: "आयोजित रक्तदान शिबिरे",
            stat_donors_label: "नोंदणीकृत ऐच्छिक रक्तदाते",
            tab1_title: "रिअल-टाइम रक्त साठा उपलब्धता शोध",
            tab1_desc: "आपल्या जिल्ह्यातील परवानाधारक रक्तपेढ्यांमधील पडताळलेला रक्तसाठा तपासा.",
            tab1_syncing: "थेट डेटा सिंक होत आहे",
            label_state: "राज्य / केंद्रशासित प्रदेश",
            select_state_default: "-- राज्य निवडा --",
            label_district: "जिल्हा",
            select_district_default: "-- जिल्हा निवडा --",
            label_blood_group: "रक्तगट",
            all_groups: "सर्व रक्तगट",
            label_component: "रक्त घटक प्रकार",
            all_components: "सर्व घटक",
            btn_search_stock: "साठा शोधा",
            btn_reset: "रीसेट करा",
            found_prefix: "एकूण",
            found_suffix: "रक्त केंद्रे सापडली",
            legend_in_stock: "उपलब्ध (>१०)",
            legend_low_stock: "कमी साठा (३-१०)",
            legend_critical: "अत्यंत कमी (<३)",
            no_centers_title: "कोणतेही रक्त केंद्र सापडले नाही",
            no_centers_desc: "कृपया राज्य, जिल्हा किंवा घटक फिल्टर बदलून पुन्हा प्रयत्न करा.",
            btn_contact_center: "संपर्क करा",
            tab2_title: "आगामी ऐच्छिक रक्तदान शिबिरे",
            tab2_desc: "आपल्या जवळील फिरती रक्तदान मोहीम आणि शिबिरे शोधा.",
            label_filter_state: "राज्य फिल्टर",
            all_states: "सर्व राज्ये",
            label_filter_date: "दिनांक फिल्टर",
            label_search_keyword: "कीवर्ड शोधा",
            placeholder_keyword: "उदा. AIIMS, रेड क्रॉस...",
            camp_organizer_label: "आयोजक:",
            camp_slots_booked: "बुक केलेले स्लॉट्स",
            btn_book_slot: "रक्तदान स्लॉट बुक करा",
            badge_slot_confirmed: "स्लॉट निश्चित झाला",
            tab3_title: "ऐच्छिक रक्तदाता नोंदणी",
            tab3_desc: "भारताच्या केंद्रीकृत रक्तदाता डेटाबेसचा भाग व्हा.",
            label_full_name: "पूर्ण नाव *",
            label_age: "वय (वर्षे) *",
            label_gender: "लिंग *",
            select_gender_default: "-- निवडा --",
            gender_male: "पुरुष",
            gender_female: "महिला",
            gender_trans: "तृतीयपंथी",
            label_mobile: "मोबाईल क्रमांक *",
            label_email: "ईमेल पत्ता",
            label_weight: "वजन (किलो) *",
            label_last_donated: "शेवटच्या रक्तदानाची तारीख",
            donor_consent_text: "माझ्या जिल्ह्यात आपत्कालीन गरजेच्या वेळी तातडीच्या सूचना मिळण्यास मी संमती देतो/देते.",
            btn_register_donor: "नोंदणी करा आणि डिजिटल डोनर पास मिळवा",
            eligibility_title: "मी आज रक्तदान करण्यास पात्र आहे का?",
            eligibility_1: "वय १८ ते ६५ वर्षे दरम्यान",
            eligibility_2: "वजन ४५ किलोपेक्षा जास्त",
            eligibility_3: "हिमोग्लोबिन पातळी ≥ १२.५ g/dL",
            eligibility_4: "शेवटचे रक्तदान किमान ९० दिवसांपूर्वी झालेले असावे",
            eligibility_5: "कोणताही ताप किंवा संसर्ग नाही",
            eligibility_6: "गेल्या ६ महिन्यांत कोणतीही मोठी शस्त्रक्रिया नाही",
            donor_card_title: "ई-रक्तकोश ऐच्छिक डोनर कार्ड",
            donor_card_sub: "भारत सरकार • आरोग्य मंत्रालय",
            donor_card_id: "डोनर आयडी:",
            donor_card_mobile: "मोबाईल:",
            donor_card_state: "राज्य:",
            donor_card_status: "स्थिती:",
            donor_card_active_badge: "सक्रिय जीवनरक्षक",
            donor_card_scan: "रक्त केंद्रावर स्कॅन करा",
            tab4_title: "रक्तगट आणि घटक सुसंगतता मार्गदर्शक",
            tab4_desc: "योग्य रक्तदाते आणि प्राप्तकर्ते पाहण्यासाठी रक्तगट निवडा.",
            label_target_group: "तपासण्यासाठी रक्तगट निवडा:",
            give_to_title: "तांबड्या रक्तपेशी यांना देऊ शकतात:",
            receive_from_title: "तांबड्या रक्तपेशी यांच्याकडून घेऊ शकतात:",
            shelf_life_title: "रक्त घटक आणि टिकाऊपणा मार्गदर्शक",
            shelf_wb: "संपूर्ण रक्त (Whole Blood)",
            shelf_wb_days: "३५ - ४२ दिवस",
            shelf_wb_desc: "२°C ते ६°C तापमानात साठवले जाते",
            shelf_prbc: "पॅक्ड रेड सेल्स (PRBC)",
            shelf_prbc_days: "४२ दिवस",
            shelf_prbc_desc: "ऑक्सिजन वहन क्षमता वाढवते",
            shelf_platelets: "प्लेटलेट्स (SDP / RDP)",
            shelf_platelets_days: "५ दिवस",
            shelf_platelets_desc: "२०°C - २४°C तापमानात सतत हलवणे",
            shelf_ffp: "फ्रेश फ्रोझन प्लाझ्मा (FFP)",
            shelf_ffp_days: "१ वर्ष",
            shelf_ffp_desc: "-३०°C किंवा त्यापेक्षा कमी तापमानात गोठवलेले",
            tab5_title: "रक्त केंद्र व्यवस्थापन आणि इन्व्हेंटरी नियंत्रण",
            tab5_desc: "रक्तपेढी चालकांसाठी आणि आपत्कालीन पुरवठ्यासाठी अंतर्गत डॅशबोर्ड.",
            label_select_center: "रक्त केंद्र निवडा:",
            admin_stat_total: "एकूण उपलब्ध युनिट्स",
            badge_optimal: "उत्तम साठा",
            admin_stat_expiring: "७ दिवसांत मुदत संपणारे",
            badge_action_req: "कारवाई आवश्यक",
            admin_stat_pending: "प्रलंबित आपत्कालीन विनंत्या",
            badge_high_priority: "उच्च प्राधान्य",
            admin_stat_next_camp: "पुढील शिबिर",
            badge_next_camp: "एम्स कॅम्पस मोहीम",
            th_blood_group: "रक्तगट",
            th_whole_blood: "संपूर्ण रक्त",
            th_prbc: "PRBC",
            th_platelets: "प्लेटलेट्स",
            th_ffp: "FFP प्लाझ्मा",
            th_status: "साठा स्थिती",
            th_actions: "कारवाई",
            btn_dispatch: "SOS पाठवा",
            btn_add_unit: "+ युनिट जोडा",
            sos_modal_title: "आपत्कालीन रक्त आवश्यकता SOS",
            sos_modal_desc: "जवळपासच्या रक्तपेढ्यांना आणि नोंदणीकृत दात्यांना तातडीचा संदेश पाठवा.",
            label_patient_name: "रुग्णाचे नाव *",
            label_units_required: "आवश्यक युनिट्स *",
            label_urgency: "तातडीची कालमर्यादा *",
            label_hospital: "रुग्णालयाचे नाव व पत्ता *",
            label_contact_doctor: "डॉक्टर / नातेवाईकाचे नाव *",
            label_contact_mobile: "संपर्क फोन *",
            btn_cancel: "रद्द करा",
            btn_broadcast: "आपत्कालीन SOS पाठवा",
            booking_modal_title: "रक्तदान अपॉइंटमेंट बुक करा",
            label_booking_donor_name: "रक्तदात्याचे नाव *",
            label_pref_slot: "पसंतीची वेळ स्लॉट *",
            btn_confirm_slot: "स्लॉट निश्चित करा व पास मिळवा",
            footer_brand_desc: "राष्ट्रीय आरोग्य अभियान, आरोग्य व कुटुंब कल्याण मंत्रालय, भारत सरकार अंतर्गत केंद्रीकृत रक्त केंद्र व्यवस्थापन प्रणाली.",
            footer_quick_portals: "जलद पोर्टल्स",
            footer_stock_link: "रक्त साठा उपलब्धता",
            footer_camps_link: "ऐच्छिक रक्तदान शिबिरे",
            footer_donor_link: "रक्तदाता नोंदणी पोर्टल",
            footer_compat_link: "रक्त सुसंगतता मार्गदर्शक",
            footer_admin_link: "ब्लड बँक लॉगिन",
            footer_helpdesk: "हेल्पडेस्क मदत",
            footer_helpline: "आपत्कालीन हेल्पलाइन:",
            footer_email: "ईमेल:",
            footer_tech_cell: "सी-डॅक आणि आरोग्य मंत्रालय तांत्रिक कक्ष",
            footer_copy: "© २०२६ ई-रक्तकोश • आरोग्य व कुटुंब कल्याण मंत्रालय. सर्व हक्क राखीव.",
            footer_tagline: "अचूकता आणि आपत्कालीन सुलभतेने तयार केलेले",
            toast_lang_switched: "भाषा बदलली आहे:"
        }
    }
};
